-- ============================================================
-- V1__schema_and_seed_data.sql
-- Single consolidated migration: schema + all seed data
-- ============================================================

-- ------------------------------------------------------------
-- SCHEMA
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS category (
    id INTEGER PRIMARY KEY,
    category_name TEXT UNIQUE
);
CREATE TABLE IF NOT EXISTS unit (
    id INTEGER PRIMARY KEY,
    unit_name TEXT UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS recipe (
    id INTEGER PRIMARY KEY,
    name TEXT UNIQUE,
    servings INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS item (
    id INTEGER PRIMARY KEY,
    name TEXT,
    category_id INTEGER,
    unit_id INTEGER,
    UNIQUE (name, unit_id),
    FOREIGN KEY (category_id) REFERENCES category(id),
    FOREIGN KEY (unit_id) REFERENCES unit(id)
);
CREATE TABLE IF NOT EXISTS recipe_item (
    id INTEGER PRIMARY KEY,
    recipe_id INTEGER,
    item_id INTEGER,
    quantity FLOAT,
    FOREIGN KEY (recipe_id) REFERENCES recipe(id),
    FOREIGN KEY (item_id) REFERENCES item(id)
);
CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER PRIMARY KEY,
    item_id INTEGER,
    quantity FLOAT,
    deleted INTEGER,
    FOREIGN KEY (item_id) REFERENCES item(id)
);

DELETE FROM shopping_list;
DELETE FROM recipe_item;
DELETE FROM item;
DELETE FROM recipe;
DELETE FROM category;
DELETE FROM unit;
-- ------------------------------------------------------------
-- UNITS
-- ------------------------------------------------------------
INSERT INTO unit (id, unit_name) VALUES (1, 'g');
INSERT INTO unit (id, unit_name) VALUES (2, 'ml');
INSERT INTO unit (id, unit_name) VALUES (3, 'pcs');

-- ------------------------------------------------------------
-- CATEGORIES
-- ------------------------------------------------------------
INSERT INTO category (id, category_name) VALUES (1, 'Bakery');
INSERT INTO category (id, category_name) VALUES (2, 'Canned Goods');
INSERT INTO category (id, category_name) VALUES (3, 'Carbs');
INSERT INTO category (id, category_name) VALUES (4, 'Dairy');
INSERT INTO category (id, category_name) VALUES (5, 'Fish');
INSERT INTO category (id, category_name) VALUES (6, 'Fruit');
INSERT INTO category (id, category_name) VALUES (7, 'Meat');
INSERT INTO category (id, category_name) VALUES (8, 'Nuts');
INSERT INTO category (id, category_name) VALUES (9, 'Oils');
INSERT INTO category (id, category_name) VALUES (10, 'Paste');
INSERT INTO category (id, category_name) VALUES (11, 'Sauce');
INSERT INTO category (id, category_name) VALUES (12, 'Spices');
INSERT INTO category (id, category_name) VALUES (13, 'Vegetables');

-- ------------------------------------------------------------
-- ITEMS
-- ------------------------------------------------------------
INSERT INTO item (id, name, category_id, unit_id) VALUES (1, 'Sourdough Bread', 1, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (2, 'Tortilla Wrap', 1, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (3, 'Black Beans', 2, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (4, 'Cannellini Beans', 2, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (5, 'Chopped Tomatoes', 2, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (6, 'Condensed Chicken Soup', 2, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (7, 'Condensed Tomato Soup', 2, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (8, 'Green Chiles', 2, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (9, 'Kidney Beans', 2, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (10, 'Lentils', 2, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (11, 'Passata', 2, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (12, 'Sun-Dried Tomatoes', 2, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (13, 'Bread', 3, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (14, 'Couscous', 3, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (15, 'Gnocchi', 3, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (16, 'Linguine', 3, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (17, 'Noodles', 3, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (18, 'Orzo', 3, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (19, 'Pasta', 3, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (20, 'Prawn Crackers', 3, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (21, 'Rice', 3, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (22, 'Rigatoni', 3, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (23, 'Risotto Rice', 3, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (24, 'Tortilla Chips', 3, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (25, 'Cheddar', 4, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (26, 'Cheese', 4, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (27, 'Cheese Triangle', 4, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (28, 'Coconut Milk', 2, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (29, 'Cream', 4, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (30, 'Creme Fraiche', 4, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (31, 'Double Cream', 4, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (32, 'Egg', 4, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (33, 'Greek Yogurt', 4, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (34, 'Halloumi', 4, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (35, 'Mayonnaise', 4, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (36, 'Parmesan', 4, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (37, 'Single Cream', 4, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (38, 'Soft Cheese', 4, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (39, 'Sour Cream', 4, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (40, 'King Prawn', 5, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (41, 'Prawn', 5, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (42, 'Salmon', 5, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (43, 'Lemon', 6, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (44, 'Lime', 6, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (45, 'Chicken Thigh', 7, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (46, 'Bacon', 7, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (47, 'Beef Mince', 7, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (48, 'Beef Steak', 7, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (49, 'Braising Steak', 7, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (50, 'Chicken', 7, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (51, 'Chicken Breast', 7, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (52, 'Chicken Sausage', 7, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (53, 'Chorizo', 7, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (54, 'Lamb Mince', 7, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (55, 'Turkey Mince', 7, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (56, 'Peanut', 8, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (57, 'Peanut Butter', 8, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (58, 'Pistachio', 8, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (59, 'Olive Oil', 9, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (60, 'Chipotle Paste', 10, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (61, 'Curry Paste', 10, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (62, 'Garlic Paste', 10, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (63, 'Ginger Paste', 10, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (64, 'Gochujang Paste', 10, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (65, 'Katsu Curry Paste', 10, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (66, 'Tamarind Paste', 10, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (67, 'Thai Red Curry Paste', 10, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (68, 'Tikka Masala Paste', 10, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (69, 'Tomato Paste', 10, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (70, 'BBQ Sauce', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (71, 'Beef Stock Cube', 11, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (72, 'Dark Beer', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (73, 'Dark Chocolate', 11, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (74, 'Dark Soy Sauce', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (75, 'Dijon Mustard', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (76, 'Fajita Sauce', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (77, 'Fish Sauce', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (78, 'Gravy Granules', 11, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (79, 'Hoisin Sauce', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (80, 'Honey', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (81, 'Lemon And Herb Sauce', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (82, 'Liquid Smoke', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (83, 'Mango Chutney', 11, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (84, 'Maple Syrup', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (85, 'Mint Sauce', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (86, 'Oyster Sauce', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (87, 'Peri-Peri Sauce', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (88, 'Rice Wine Vinegar', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (89, 'Salsa Verde', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (90, 'Sesame Oil', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (91, 'Soy Sauce', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (92, 'Sriracha', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (93, 'Sriracha Mayo', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (94, 'Sweet Chilli Sauce', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (95, 'Tomato Ketchup', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (96, 'Tomato Puree', 11, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (97, 'Vegetable Broth', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (98, 'White Wine', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (99, 'Worcestershire Sauce', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (100, 'Chicken Stock', 11, 2);
INSERT INTO item (id, name, category_id, unit_id) VALUES (101, 'BBQ Seasoning', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (102, 'Cajun Seasoning', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (103, 'Cayenne Pepper', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (104, 'Chilli Flakes', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (105, 'Chilli Powder', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (106, 'Cornflour', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (107, 'Cornstarch', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (108, 'Cumin', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (109, 'Curry Powder', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (110, 'Fajita Seasoning', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (111, 'Garam Masala', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (112, 'Garlic Powder', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (113, 'Italian Seasoning', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (114, 'Mixed Herbs', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (115, 'Onion Powder', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (116, 'Oregano', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (117, 'Paprika', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (118, 'Plain Flour', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (119, 'Rosemary', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (120, 'Sesame Seeds', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (121, 'Smoked Paprika', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (122, 'Tandoori Spice Mix', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (123, 'Turmeric', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (124, 'White Pepper', 12, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (125, 'Asparagus', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (126, 'Baby Corn', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (127, 'Basil', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (128, 'Beansprouts', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (129, 'Bell Pepper', 13, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (130, 'Broccoli', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (131, 'Carrot', 13, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (132, 'Cauliflower Rice', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (133, 'Celery', 13, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (134, 'Cherry Tomato', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (135, 'Chilli', 13, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (136, 'Chives', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (137, 'Cilantro', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (138, 'Frozen Peas', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (139, 'Garlic', 13, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (140, 'Green Beans', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (141, 'Jalapeno', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (142, 'Leek', 13, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (143, 'Lettuce', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (144, 'Mushroom', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (145, 'Onion', 13, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (146, 'Parsley', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (147, 'Peas', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (148, 'Poblano Pepper', 13, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (149, 'Potato', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (150, 'Red Onion', 13, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (151, 'Shallot', 13, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (152, 'Spinach', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (153, 'Spring Onion', 13, 3);
INSERT INTO item (id, name, category_id, unit_id) VALUES (154, 'Sugar Snap Peas', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (155, 'Sweet Potato', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (156, 'Tomato', 13, 1);
INSERT INTO item (id, name, category_id, unit_id) VALUES (157, 'Turnip', 13, 3);

-- ------------------------------------------------------------
-- RECIPES
-- ------------------------------------------------------------
INSERT INTO recipe (id, name, servings) VALUES (1, 'Black And Blue Soup', 8);
INSERT INTO recipe (id, name, servings) VALUES (2, 'White Chicken Chili', 6);
INSERT INTO recipe (id, name, servings) VALUES (3, 'Stuffed Peppers', 4);
INSERT INTO recipe (id, name, servings) VALUES (4, 'Chipotle Beefy Noodles', 4);
INSERT INTO recipe (id, name, servings) VALUES (5, 'Crispy Chilli Turkey And Udon Noodles', 4);
INSERT INTO recipe (id, name, servings) VALUES (6, 'Beefy Fried Rice', 4);
INSERT INTO recipe (id, name, servings) VALUES (7, 'Mental Lentil Soup', 5);
INSERT INTO recipe (id, name, servings) VALUES (8, 'Chicken Chorizo And Sweet Potato Soup', 6);
INSERT INTO recipe (id, name, servings) VALUES (9, 'Chicken Sausage Garlic And Herb Pasta', 4);
INSERT INTO recipe (id, name, servings) VALUES (10, 'Creamy King Prawn Pasta', 4);
INSERT INTO recipe (id, name, servings) VALUES (11, 'Creamy Halloumi Linguine', 4);
INSERT INTO recipe (id, name, servings) VALUES (12, 'Gnocchi Bolognese', 4);
INSERT INTO recipe (id, name, servings) VALUES (13, 'Double-Decker Chicken And Bacon Pie', 6);
INSERT INTO recipe (id, name, servings) VALUES (14, 'Sweet Potato Shepherds Pie', 4);
INSERT INTO recipe (id, name, servings) VALUES (15, 'Barbecue Chicken Wraps', 4);
INSERT INTO recipe (id, name, servings) VALUES (16, 'Peri-Peri Chicken Salad', 2);
INSERT INTO recipe (id, name, servings) VALUES (17, 'Slow Cooker Beef Stew', 4);
INSERT INTO recipe (id, name, servings) VALUES (18, 'Slow Cooker Fajita Orzo', 4);
INSERT INTO recipe (id, name, servings) VALUES (19, 'Slow Cooker Deconstructed Enchiladas', 4);
INSERT INTO recipe (id, name, servings) VALUES (20, 'Thick And Chunky Chilli Con Carne', 4);
INSERT INTO recipe (id, name, servings) VALUES (21, 'Creamy Curried Chicken And Couscous', 4);
INSERT INTO recipe (id, name, servings) VALUES (22, 'Salmon Traybake', 4);
INSERT INTO recipe (id, name, servings) VALUES (23, 'Chicken Curry Traybake', 4);
INSERT INTO recipe (id, name, servings) VALUES (24, 'Thai Red Curry Traybake', 4);
INSERT INTO recipe (id, name, servings) VALUES (25, 'Katsu Curry Traybake', 4);
INSERT INTO recipe (id, name, servings) VALUES (26, 'Chilli Heatwave Bang Bang Traybake', 4);
INSERT INTO recipe (id, name, servings) VALUES (27, 'Chicken Tikka Chasni', 2);
INSERT INTO recipe (id, name, servings) VALUES (28, 'Chicken Chow Mein', 4);
INSERT INTO recipe (id, name, servings) VALUES (29, 'Chicken Satay And Coconut Rice', 2);
INSERT INTO recipe (id, name, servings) VALUES (30, 'Gochujang Turkey Mince And Coconut Rice', 4);
INSERT INTO recipe (id, name, servings) VALUES (31, 'Chilli Chicken', 4);
INSERT INTO recipe (id, name, servings) VALUES (32, 'Chicken in Oyster Sauce', 4);
INSERT INTO recipe (id, name, servings) VALUES (33, 'Beef and Broccoli', 4);
INSERT INTO recipe (id, name, servings) VALUES (34, 'Garlic Chilli Prawn Linguine', 4);
INSERT INTO recipe (id, name, servings) VALUES (35, 'Quick Chicken and Chorizo Paella', 4);
INSERT INTO recipe (id, name, servings) VALUES (36, 'Creamy Chicken and Garlic Pasta', 4);
INSERT INTO recipe (id, name, servings) VALUES (37, 'Smoked Salmon Hash', 2);
INSERT INTO recipe (id, name, servings) VALUES (38, 'Creamy Eggs on Toast', 1);
INSERT INTO recipe (id, name, servings) VALUES (39, 'Crispy Turkey Stir Fry', 4);
INSERT INTO recipe (id, name, servings) VALUES (40, 'Coconut Chicken Curry', 4);
INSERT INTO recipe (id, name, servings) VALUES (41, 'Pistachio Crusted Salmon with Lemon Peas', 4);
INSERT INTO recipe (id, name, servings) VALUES (42, 'Beef Stroganoff', 4);
INSERT INTO recipe (id, name, servings) VALUES (43, 'Chicken Pad Thai', 4);
INSERT INTO recipe (id, name, servings) VALUES (44, 'Sweet Chilli Chicken Noodles', 4);
INSERT INTO recipe (id, name, servings) VALUES (45, 'Peanut Chicken', 4);
INSERT INTO recipe (id, name, servings) VALUES (46, 'Creamy Cajun Chicken Pasta', 4);
INSERT INTO recipe (id, name, servings) VALUES (47, 'Chicken and Chorizo Rigatoni', 4);
INSERT INTO recipe (id, name, servings) VALUES (48, 'Carbonara Orzo', 4);
INSERT INTO recipe (id, name, servings) VALUES (49, 'Creamy Garlic Chicken and Chorizo Orzo', 4);
INSERT INTO recipe (id, name, servings) VALUES (50, 'Salmon Risotto', 4);

-- ------------------------------------------------------------
-- RECIPE ITEMS
-- ------------------------------------------------------------
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (1, 1, 151, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (2, 1, 133, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (3, 1, 129, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (4, 1, 139, 6);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (5, 1, 44, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (6, 1, 137, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (7, 1, 3, 454);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (8, 1, 97, 1440);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (9, 1, 84, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (10, 1, 108, 9);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (11, 1, 105, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (12, 1, 26, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (13, 1, 39, 120);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (14, 2, 148, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (15, 2, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (16, 2, 139, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (17, 2, 50, 1134);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (18, 2, 100, 960);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (19, 2, 89, 240);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (20, 2, 44, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (21, 2, 8, 198);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (22, 2, 84, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (23, 2, 82, 2.5);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (24, 2, 4, 870);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (25, 2, 108, 6);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (26, 2, 105, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (27, 2, 107, 27);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (28, 2, 33, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (29, 2, 26, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (30, 2, 137, 10);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (31, 3, 129, 4);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (32, 3, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (33, 3, 139, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (34, 3, 47, 454);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (35, 3, 112, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (36, 3, 113, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (37, 3, 116, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (38, 3, 99, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (39, 3, 69, 226);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (40, 3, 96, 170);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (41, 3, 132, 150);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (42, 3, 26, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (43, 4, 47, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (44, 4, 117, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (45, 4, 112, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (46, 4, 115, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (47, 4, 62, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (48, 4, 63, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (49, 4, 60, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (50, 4, 91, 80);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (51, 4, 80, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (52, 4, 135, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (53, 4, 153, 5);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (54, 4, 17, 450);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (55, 5, 55, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (56, 5, 62, 6);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (57, 5, 63, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (58, 5, 80, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (59, 5, 91, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (60, 5, 94, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (61, 5, 17, 450);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (62, 5, 131, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (63, 5, 153, 4);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (64, 5, 44, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (65, 6, 47, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (66, 6, 108, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (67, 6, 112, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (68, 6, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (69, 6, 21, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (70, 6, 62, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (71, 6, 91, 90);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (72, 6, 94, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (73, 6, 80, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (74, 6, 92, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (75, 6, 79, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (76, 7, 50, 400);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (77, 7, 100, 2000);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (78, 7, 10, 240);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (79, 7, 131, 5);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (80, 7, 142, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (81, 8, 50, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (82, 8, 53, 100);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (83, 8, 100, 2500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (84, 8, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (85, 8, 139, 4);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (86, 8, 131, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (87, 8, 129, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (88, 8, 155, 700);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (89, 8, 105, 22);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (90, 8, 109, 22);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (91, 9, 52, 10);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (92, 9, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (93, 9, 139, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (94, 9, 116, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (95, 9, 22, 260);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (96, 9, 7, 295);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (97, 9, 38, 100);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (98, 10, 22, 280);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (99, 10, 62, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (100, 10, 63, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (101, 10, 135, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (102, 10, 40, 450);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (103, 10, 44, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (104, 10, 38, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (105, 10, 152, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (106, 10, 12, 100);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (107, 11, 16, 260);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (108, 11, 59, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (109, 11, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (110, 11, 139, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (111, 11, 34, 225);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (112, 11, 117, 22);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (113, 11, 113, 22);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (114, 11, 104, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (115, 11, 69, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (116, 11, 97, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (117, 11, 38, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (118, 12, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (119, 12, 131, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (120, 12, 133, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (121, 12, 47, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (122, 12, 144, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (123, 12, 69, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (124, 12, 139, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (125, 12, 104, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (126, 12, 5, 400);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (127, 12, 37, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (128, 12, 15, 800);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (129, 12, 36, 12);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (130, 13, 149, 1200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (131, 13, 50, 800);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (132, 13, 46, 240);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (133, 13, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (134, 13, 6, 590);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (135, 13, 25, 150);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (136, 13, 78, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (137, 13, 131, 4);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (138, 14, 155, 800);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (139, 14, 54, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (140, 14, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (141, 14, 139, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (142, 14, 131, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (143, 14, 69, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (144, 14, 113, 6);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (145, 14, 100, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (146, 14, 147, 80);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (147, 14, 38, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (148, 14, 25, 40);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (149, 14, 36, 50);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (150, 15, 50, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (151, 15, 101, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (152, 15, 129, 4);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (153, 15, 70, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (154, 15, 80, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (155, 15, 27, 4);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (156, 15, 152, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (157, 15, 2, 4);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (158, 16, 50, 300);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (159, 16, 117, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (160, 16, 112, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (161, 16, 87, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (162, 16, 80, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (163, 16, 33, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (164, 16, 81, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (165, 16, 43, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (166, 16, 94, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (167, 16, 143, 300);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (168, 16, 129, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (169, 16, 134, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (170, 16, 32, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (171, 17, 49, 700);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (172, 17, 118, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (173, 17, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (174, 17, 139, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (175, 17, 131, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (176, 17, 157, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (177, 17, 72, 440);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (178, 17, 71, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (179, 17, 69, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (180, 17, 99, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (181, 18, 50, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (182, 18, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (183, 18, 139, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (184, 18, 129, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (185, 18, 135, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (186, 18, 110, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (187, 18, 76, 340);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (188, 18, 18, 240);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (189, 18, 100, 700);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (190, 18, 38, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (191, 18, 25, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (192, 18, 141, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (193, 19, 47, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (194, 19, 9, 800);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (195, 19, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (196, 19, 129, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (197, 19, 69, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (198, 19, 11, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (199, 19, 71, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (200, 19, 116, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (201, 19, 112, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (202, 19, 117, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (203, 19, 108, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (204, 19, 105, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (205, 19, 2, 4);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (206, 19, 25, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (207, 19, 153, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (208, 19, 141, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (209, 20, 49, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (210, 20, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (211, 20, 139, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (212, 20, 5, 800);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (213, 20, 116, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (214, 20, 108, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (215, 20, 117, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (216, 20, 105, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (217, 20, 71, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (218, 20, 9, 400);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (219, 20, 73, 20);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (220, 20, 30, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (221, 21, 50, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (222, 21, 6, 295);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (223, 21, 35, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (224, 21, 31, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (225, 21, 109, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (226, 21, 25, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (227, 21, 14, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (228, 22, 149, 800);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (229, 22, 113, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (230, 22, 142, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (231, 22, 42, 480);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (232, 22, 112, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (233, 22, 43, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (234, 22, 125, 100);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (235, 22, 30, 150);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (236, 23, 50, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (237, 23, 109, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (238, 23, 21, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (239, 23, 138, 100);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (240, 23, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (241, 23, 129, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (242, 23, 62, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (243, 23, 91, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (244, 23, 61, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (245, 23, 28, 400);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (246, 23, 100, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (247, 24, 50, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (248, 24, 105, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (249, 24, 112, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (250, 24, 21, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (251, 24, 129, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (252, 24, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (253, 24, 138, 100);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (254, 24, 100, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (255, 24, 67, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (256, 24, 28, 400);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (257, 25, 50, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (258, 25, 65, 70);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (259, 25, 21, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (260, 25, 138, 100);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (261, 25, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (262, 25, 129, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (263, 25, 139, 5);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (264, 25, 91, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (265, 25, 28, 400);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (266, 25, 100, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (267, 26, 50, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (268, 26, 21, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (269, 26, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (270, 26, 129, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (271, 26, 35, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (272, 26, 94, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (273, 26, 112, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (274, 26, 102, 22);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (275, 26, 105, 22);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (276, 26, 100, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (277, 26, 92, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (278, 26, 24, 70);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (279, 26, 26, 80);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (280, 27, 50, 300);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (281, 27, 68, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (282, 27, 122, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (283, 27, 5, 400);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (284, 27, 83, 70);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (285, 27, 123, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (286, 27, 111, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (287, 27, 105, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (288, 27, 108, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (289, 27, 95, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (290, 27, 62, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (291, 27, 63, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (292, 27, 85, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (293, 27, 37, 75);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (294, 27, 44, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (295, 27, 21, 250);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (296, 27, 137, 10);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (297, 28, 32, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (298, 28, 106, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (299, 28, 91, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (300, 28, 124, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (301, 28, 50, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (302, 28, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (303, 28, 153, 5);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (304, 28, 139, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (305, 28, 17, 450);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (306, 28, 74, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (307, 28, 128, 100);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (308, 28, 20, 40);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (309, 29, 57, 50);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (310, 29, 67, 40);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (311, 29, 91, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (312, 29, 28, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (313, 29, 50, 300);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (314, 29, 21, 250);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (315, 30, 55, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (316, 30, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (317, 30, 64, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (318, 30, 91, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (319, 30, 62, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (320, 30, 63, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (321, 30, 80, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (322, 30, 153, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (323, 30, 21, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (324, 30, 93, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (325, 30, 120, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (326, 31, 45, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (327, 31, 106, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (328, 31, 117, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (329, 31, 112, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (330, 31, 129, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (331, 31, 150, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (332, 31, 62, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (333, 31, 91, 120);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (334, 31, 92, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (335, 31, 94, 37);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (336, 31, 80, 37);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (337, 31, 140, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (338, 32, 51, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (339, 32, 106, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (340, 32, 90, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (341, 32, 91, 100);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (342, 32, 150, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (343, 32, 129, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (344, 32, 86, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (345, 32, 135, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (346, 32, 17, 450);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (347, 32, 120, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (348, 33, 48, 450);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (349, 33, 106, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (350, 33, 130, 400);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (351, 33, 91, 90);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (352, 33, 90, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (353, 33, 62, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (354, 33, 63, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (355, 33, 88, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (356, 33, 120, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (357, 34, 19, 260);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (358, 34, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (359, 34, 139, 5);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (360, 34, 62, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (361, 34, 135, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (362, 34, 129, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (363, 34, 156, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (364, 34, 96, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (365, 34, 121, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (366, 34, 41, 450);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (367, 34, 146, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (368, 35, 53, 80);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (369, 35, 51, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (370, 35, 150, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (371, 35, 129, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (372, 35, 156, 250);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (373, 35, 117, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (374, 35, 108, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (375, 35, 105, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (376, 35, 96, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (377, 35, 5, 400);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (378, 35, 127, 10);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (379, 36, 19, 260);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (380, 36, 151, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (381, 36, 139, 5);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (382, 36, 51, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (383, 36, 144, 250);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (384, 36, 29, 250);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (385, 36, 102, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (386, 36, 114, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (387, 36, 36, 6);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (388, 37, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (389, 37, 149, 300);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (390, 37, 42, 180);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (391, 37, 44, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (392, 37, 39, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (393, 37, 75, 5);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (394, 37, 146, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (395, 37, 136, 10);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (396, 37, 114, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (397, 37, 1, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (398, 37, 43, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (399, 38, 32, 4);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (400, 38, 33, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (401, 38, 38, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (402, 38, 117, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (403, 38, 92, 20);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (404, 38, 13, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (405, 38, 136, 10);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (406, 38, 104, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (407, 39, 55, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (408, 39, 63, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (409, 39, 139, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (410, 39, 153, 4);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (411, 39, 80, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (412, 39, 91, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (413, 39, 92, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (414, 39, 18, 300);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (415, 39, 44, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (416, 39, 137, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (417, 40, 50, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (418, 40, 109, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (419, 40, 100, 300);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (420, 40, 154, 100);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (421, 40, 126, 100);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (422, 40, 129, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (423, 40, 28, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (424, 40, 91, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (425, 40, 44, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (426, 40, 137, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (427, 40, 135, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (428, 40, 153, 6);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (429, 40, 63, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (430, 40, 139, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (431, 41, 42, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (432, 41, 43, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (433, 41, 75, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (434, 41, 80, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (435, 41, 119, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (436, 41, 58, 80);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (437, 41, 147, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (438, 41, 139, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (439, 42, 48, 500);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (440, 42, 121, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (441, 42, 106, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (442, 42, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (443, 42, 144, 400);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (444, 42, 139, 4);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (445, 42, 75, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (446, 42, 99, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (447, 42, 38, 50);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (448, 42, 100, 300);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (449, 42, 29, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (450, 42, 146, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (451, 43, 51, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (452, 43, 91, 75);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (453, 43, 86, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (454, 43, 66, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (455, 43, 77, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (456, 43, 44, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (457, 43, 112, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (458, 43, 103, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (459, 43, 151, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (460, 43, 139, 4);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (461, 43, 153, 5);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (462, 43, 17, 300);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (463, 43, 32, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (464, 43, 56, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (465, 44, 51, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (466, 44, 112, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (467, 44, 103, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (468, 44, 121, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (469, 44, 80, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (470, 44, 91, 90);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (471, 44, 150, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (472, 44, 135, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (473, 44, 153, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (474, 44, 17, 300);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (475, 44, 94, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (476, 44, 92, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (477, 44, 104, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (478, 44, 106, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (479, 45, 51, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (480, 45, 44, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (481, 45, 88, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (482, 45, 91, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (483, 45, 94, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (484, 45, 77, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (485, 45, 139, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (486, 45, 63, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (487, 45, 105, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (488, 45, 100, 250);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (489, 45, 28, 400);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (490, 45, 57, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (491, 45, 146, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (492, 46, 19, 250);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (493, 46, 51, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (494, 46, 102, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (495, 46, 121, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (496, 46, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (497, 46, 129, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (498, 46, 139, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (499, 46, 96, 45);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (500, 46, 38, 80);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (501, 46, 33, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (502, 46, 100, 130);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (503, 46, 104, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (504, 46, 137, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (505, 47, 51, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (506, 47, 121, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (507, 47, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (508, 47, 53, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (509, 47, 22, 240);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (510, 47, 96, 30);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (511, 47, 12, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (512, 47, 29, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (513, 47, 152, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (514, 47, 36, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (515, 48, 150, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (516, 48, 51, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (517, 48, 116, 6);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (518, 48, 46, 120);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (519, 48, 144, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (520, 48, 18, 240);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (521, 48, 100, 700);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (522, 48, 38, 125);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (523, 48, 36, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (524, 48, 146, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (525, 49, 53, 70);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (526, 49, 51, 600);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (527, 49, 139, 4);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (528, 49, 121, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (529, 49, 150, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (530, 49, 129, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (531, 49, 18, 240);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (532, 49, 100, 700);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (533, 49, 38, 100);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (534, 49, 137, 15);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (535, 50, 42, 520);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (536, 50, 145, 1);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (537, 50, 139, 3);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (538, 50, 23, 240);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (539, 50, 98, 200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (540, 50, 97, 1200);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (541, 50, 43, 2);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (542, 50, 36, 60);
INSERT INTO recipe_item (id, recipe_id, item_id, quantity) VALUES (543, 50, 146, 15);