logging:
  level:
    org.hibernate: INFO
spring:
  jpa:
    database-platform=org:
      hibernate:
        community:
          dialect: SQLiteDialect
    hibernate:
      hbm2ddl:
        auto: create-drop
      show_sql: false
datasource:
  driverClassName: org.sqlite.JDBC
  url: jdbc:sqlite:shopping.db
  username: sa
  password: sa
  tomcat:
    max-active: 1
flyway:
  locations: db/migration

  spring:
